#! /bin/sh

# killall polybar; polybar example &
killall polybar

polybar main &
polybar sec &

# xwallpaper --clear; xwallpaper --zoom "$HOME/.config/wallpaper.jpg" &

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
# Primary monitor
# bspc monitor DP-4 -d VI VII VIII IX X
bspc monitor DP-4 -d 6 7 8 9 10
# Secondary monitor
# bspc monitor DP-2 -d I II III IV V
bspc monitor DP-2 -d 1 2 3 4 5

bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_modifier     mod1

# bspc config normal_border_color '#ff0000'
# bspc config focused_border_color "$MAIN_CUSTOM_COLOR"
bspc config focused_border_color "#ffffff"

bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a mpv state=fullscreen
bspc rule -a mpv desktop='^2' split_ratio=0.75 split_dir=west
bspc rule -a chatterino desktop='^2' split_ratio=0.75 split_dir=east
bspc rule -a Emacs desktop='^5' state=tiled
bspc rule -a firefox desktop='^3'
bspc rule -a Steam desktop='^7' follow=on
bspc rule -a Lutris desktop='^9' follow=on
bspc rule -a Gcolor3 desktop='^4' state=floating
bspc rule -a "St:st:tmux-main.sh" desktop='^6' state=fullscreen
bspc rule -a "St:st:tmux-sec.sh" desktop='^1' state=fullscreen

# bspc rule -a mpv desktop='^7' split_ratio=0.75 split_dir=west
# bspc rule -a chatterino desktop='^7' split_ratio=0.75 split_dir=east
